### ISSUE TITLE
Just Any Ackable Message Queue?

### ISSUE THREAD

**Issue by copiousfreetime** [evanphx/eventd-rfc#1]
It sounds to me that what you are asking for is effectively ackable, authenticateable message queue?

All of the following ack messages published and have authentication in them, and they all have pretty well documented protocols.
- STOMP - http://stomp.github.io
- MQTT - http://mqtt.org
- NATS - http://nats.io
- NSQ - http://nsq.io

**Comment by evanphx** [comment]
Of all those, MQTT is probably the only one designed to run over the internet (though the others probably could). They're all doable as transports, but introduce additional implementation difficulties since they all require some kind of broker.

This RFC is about craft a view of a format and protocol to replace syslog. An implementation that used one of these brokers on the aggregator side would be totally fine, but the RFC needs to be generic enough to not tie users down to one of those specifics queues.
