### ISSUE TITLE
Missing some context, maybe?

### ISSUE THREAD

**Issue by jordansissel** [evanphx/eventd-rfc#3]
Replacing syslog - syslog is many things (/dev/log reader, a service that receives logs, multiple protocols, etc). Is this a replacement for all of these, or just some or one?

When I read the goals, it feels like the transport is what you want to improve, but reading the landscape sections it talks more about the software (logstash, heka, etc) and less about the transport behaviors/protocols.

**Comment by evanphx** [comment]
A good question (as always).

I tried to enumerate that with the Goals section, but I see this project as trying to:
- Design a replacement for the syslog wire protocols (all of them)
- Design a common transport for the the formatted data
- Bring consensus to how structured logging data is formatted.

I agree, the software analysis covers beyond the state goals. That's mostly because it's a brain dump, it's me looking at what those things do well within the larger context of logging. Those details can be important when looking at how to achieve the stated goals.

**Comment by jordansissel** [comment]
Ok cool, I think I understand better now :)
